# Rimuovi queste se JPA e il datasource non sono più necessari per l'idempotenza
# spring.datasource.url=jdbc:postgresql://localhost:5432/camel
# spring.datasource.username=cameluser
# spring.datasource.password=camelpass
# spring.datasource.driver-class-name=org.postgresql.Driver
# spring.jpa.hibernate.ddl-auto=update

spring.main.banner-mode=off
logging.level.root=INFO
logging.level.org.apache.camel=DEBUG
camel.springboot.main-run-controller=true

# Nuove proprietà per configurare i percorsi (opzionale, ma buona pratica)
myapp.camel.file.input.directory=src/main/resources/input
myapp.camel.file.processing.directory=src/main/resources/processing