spring.datasource.url=jdbc:postgresql://localhost:5432/camel
spring.datasource.username=cameluser
spring.datasource.password=camelpass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.main.banner-mode=off

logging.level.root=INFO
logging.level.org.apache.camel=DEBUG
camel.springboot.main-run-controller=true

spring.jpa.hibernate.ddl-auto=update
